name: Build, Test, and Push Docker image

on:
  push:
    branches:
      - grazzer # Adjust this as necessary

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Calculate next version
      id: next-version
      run: |
        LATEST_TAG=$(git tag --sort=-version:refname | head -n 1)
        if [[ -z "$LATEST_TAG" ]]; then
          NEXT_VERSION="0.0.1"
        else
          NEXT_VERSION=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF = $NF + 1 ; print}')
        fi
        echo "Next version: $NEXT_VERSION"
        echo "::set-output name=version::$NEXT_VERSION"

    - name: Build and Push the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/allthingsclowd/py-rats-chest:${{ steps.next-version.outputs.version }} . --push

    - name: Run container for testing
      run: |
        docker run --name py-rats-chest -d -p 8080:5000 ghcr.io/allthingsclowd/py-rats-chest:${{ steps.next-version.outputs.version }}
        sleep 5 # Give it some time to start up

    - name: Test container endpoints
      run: |
        curl -X POST --fail http://localhost:8080/generate_traffic || { echo 'generate_traffic test failed'; exit 1; }
        curl -X POST --fail http://localhost:8080/deploy_malware || { echo 'deploy_malware test failed'; exit 1; }
        curl -X POST --fail http://localhost:8080/deploy_nmap || { echo 'deploy_nmap test failed'; exit 1; }
        curl -X POST --fail http://localhost:8080/read_passwords || { echo 'read_passwords test failed'; exit 1; }

