name: Build, Push and Deploy to Google Cloud Run

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1 # Change this to your Google Cloud region
  IMAGE_NAME: py-rats-chest
  IMAGE_TAG: 0.0.7
  SERVICE_NAME: py-rats-chest-service

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Optionally, build your Docker image if it's not already built
    - name: Build the Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: $GCP_PROJECT_ID
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Tag and Push to Google Container Registry
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
        docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG \
          --platform managed \
          --region $GCP_REGION \
          --allow-unauthenticated \
          --project $GCP_PROJECT_ID
